on: [ push, pull_request ]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: packages
        run: |
          sudo apt-get install xcftools libpng16-16 webp
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: build
        run: |
          make
